name: Create TODO Issues

permissions:
  issues: write
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  todo-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Search for TODOs
        run: |
          grep -rni "TODO" . > todos.txt || true

      - name: Create issues for TODOs
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "TODO found in codebase"
          content-filepath: todos.txt
          labels: todo, automated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
